### ISSUE TITLE
总是卡住怎么办

### ISSUE THREAD

**Issue by BeautifulNewWorld** [Tencent/loli_profiler#10]
![image](https://user-images.githubusercontent.com/20639392/118108070-22baa380-b412-11eb-83cc-05a54daab220.png)

**Comment by sindney** [comment]
程序会在activity onResume时打断点，可以试一下把app缩小到后台再唤醒
不行的话就是设置有问题

**Comment by cfryan1990** [comment]
改下loli_profiler在mac中的磁盘访问权限，可以解决

**Comment by sindney** [comment]
> 改下loli_profiler在mac中的磁盘访问权限，可以解决

:grin: ok
