### ISSUE TITLE
一直卡在Injecting libloli.so xxx

### ISSUE THREAD

**Issue by liminwanqing** [Tencent/loli_profiler#13]
launch之后就一直卡在
Injecting libloli.so xxx

**Comment by sindney** [comment]
1. 确认下配置是否正确，确认app是debuggable=true
2. 确认下是否有开Android Studio等工具
3. 按照 https://github.com/Tencent/loli_profiler/blob/master/src/startappprocess.cpp 这里的步骤手动执行以下注入流程
4. 可看看exe旁的log文件

**Comment by liminwanqing** [comment]
> 1. 确认下配置是否正确，确认app是debuggable=true
> 2. 确认下是否有开Android Studio等工具
> 3. 按照 https://github.com/Tencent/loli_profiler/blob/master/src/startappprocess.cpp 这里的步骤手动执行以下注入流程
> 4. 可看看exe旁的log文件

好的，我试试

**Comment by liminwanqing** [comment]
> 1. 确认下配置是否正确，确认app是debuggable=true
> 2. 确认下是否有开Android Studio等工具
> 3. 按照 https://github.com/Tencent/loli_profiler/blob/master/src/startappprocess.cpp 这里的步骤手动执行以下注入流程
> 4. 可看看exe旁的log文件

现在可以了，但是so这边都是unknown，我再白名单里面有配置so的

**Comment by sindney** [comment]
root机？是不是这个原因
https://github.com/Tencent/loli_profiler/issues/2
