### ISSUE TITLE
launch后采集几秒钟数据就断开了

### ISSUE THREAD

**Issue by jefferson0228** [Tencent/loli_profiler#14]
每次launch成功后几秒钟就断连接了，日志如下：
Starting application ...
Application Started!
Connecting to application server ... 
Connection lost ...
Kill your app or re-plug USB cable and try again.
Error occurred when capturing screenshot ...
下面是我的配置
![image](https://user-images.githubusercontent.com/85483167/120983566-65bb2d00-c7ac-11eb-83bb-a08c0daefd80.png)

**Comment by sindney** [comment]
1. 确认你是armv7架构
2. 黑名单模式需要排除所有gcc编译的so库，否则会有crash问题（除非你很了解原理，否则不建议直接使用黑名单模式，黑名单模式是给no_stack模式用的）
3. 需要看手机上的log，adb logcat -s Loli
4. 断开就是手机上的server没有拉起，仍然会是配置错误的问题
5. 建议从hook单个库开始使用

**Comment by jefferson0228** [comment]
多谢，确定是armv7，我再试试白名单

**Comment by jefferson0228** [comment]
这次用白名单依然不行，log如下
C:\Users\zhouyuqiao>adb logcat -s Loli
--------- beginning of system
--------- beginning of main
06-07 17:50:52.180 17048 17048 I Loli    : JNI_OnLoad
06-07 17:50:52.180 17048 17048 I Loli    : mode: 1, build: default, minRecSize: 1024, blacklist: 0, hookLibs: libgnustl_shared,
06-07 17:50:52.180 17048 17048 I Loli    : start.bind -1
06-07 17:50:52.180 17048 17048 I Loli    : loli start status -1
06-07 17:50:52.189 17048 17159 I Loli    : libgnustl_shared (/data/app/com.gala.video-1/lib/arm/libgnustl_shared.so) is loaded
06-07 17:50:52.201 17048 17159 I Loli    : /data/app/com.gala.video-1/lib/arm/libgnustl_shared.so loaded in Android at 0x90689000
06-07 17:50:52.217 17048 17159 I Loli    : All desired libraries are loaded.
配置如下：
![image](https://user-images.githubusercontent.com/85483167/120997037-77570180-c7b9-11eb-84fc-6306f8e0508f.png)

只有几秒钟的数据
![image](https://user-images.githubusercontent.com/85483167/120997149-8d64c200-c7b9-11eb-8aee-d109e53a3876.png)

**Comment by sindney** [comment]
06-07 17:50:52.180 17048 17048 I Loli : start.bind -1
06-07 17:50:52.180 17048 17048 I Loli : loli start status -1
socket没有拉起，你的app没法open socket -1
是不是没开internet权限

**Comment by sindney** [comment]
ps 你的app设置的是用llvm/clang编译的
但是你去hook一个gcc的libgnu_stl库，你用clang去hook gcc 我刚说了 会崩的，libunwind相关 abi不兼容
libgnu_stl也应该是ndkr20不支持的库，最好通过maps或者解压apk看看你真正能hook的库

**Comment by jefferson0228** [comment]
好的，我再试试看，谢了
