### ISSUE TITLE
为什么使用Show Leaks却展示不出来内存泄漏

### ISSUE THREAD

**Issue by lijunhuawhu** [Tencent/loli_profiler#16]
大神，您好，对于Show Leaks这个功能的使用，我有些不明白。
![image](https://user-images.githubusercontent.com/7676643/126620455-811958b5-bc7e-4531-a3b0-ddfd7d455912.png)

下面是您文档上写的操作方法：
![image](https://user-images.githubusercontent.com/7676643/126620545-d2b826a2-2683-490c-852a-4202509417a7.png)

下面是我的操作。在选中的这段时间内，是存在内存泄漏的，为什么使用Show Leaks却展示不出来内存泄漏？
![image](https://user-images.githubusercontent.com/7676643/126620395-f07051c2-d67c-45af-b300-464fc1f6f51f.png)

**Comment by sindney** [comment]
两次进入相同问题函数，diff两次结束时内存记录
他是寻找完全相同调用堆栈的申请记录，然后判断malloc的count是不是增加了
增加了就是有可能泄漏了

**Comment by sindney** [comment]
有疑问再reopen
