### ISSUE TITLE
能不能增加一个体现native虚拟内存的曲线

### ISSUE THREAD

**Issue by lijunhuawhu** [Tencent/loli_profiler#17]
大神，我还有一个问题。在我的Demo中，有一个按钮，每点击一次，就使用malloc()分配了100M的内存，并且没有使用free()释放；我连续点击了很多次，但是在这个NativeHeap曲线上没有任何变化，一直是平的。经过验证，我发现NativeHeap是PSS内存，代表的是物理内存的大小，而malloc()分配的内存在没有写入内容前，是虚拟内存。
实际上，在App的使用中，也存在很多这个使用malloc()分配虚拟内存导致的泄漏，能不能增加一个体现native虚拟内存的曲线呢？
![image](https://user-images.githubusercontent.com/7676643/126621285-db954a6e-a85a-4c7a-a577-60839753bfbb.png)

**Comment by sindney** [comment]
嗯 malloc你申请了大内存，没有用的话，应该是没有建立内存映射的，所以只会提现到虚拟内存的VSS上，但现在都是64位了
虚拟内存的地址空间问题不那么严峻了，主要是我担心加了VSS会把这个LineChart推的很高，就看不到别的指标的变化了
这个图其实就是用meminfo的数据画的，可以看源码
