### ISSUE TITLE
测试大型项目时，运行几分钟后会失去tcp连接。

### ISSUE THREAD

**Issue by grystudy** [Tencent/loli_profiler#20]
我在用strict模式测试大型项目，内存申请频繁。
一般连接成功后用几分钟就会弹出：

Print("Connection lost ...");
Print("Kill your app or re-plug USB cable and try again.");

是否意味着我的程序内存申请过多，又为什么会导致断开连接。（这时我的程序没有退出，只是断开连接了）

**Comment by grystudy** [comment]
loli_server.cpp里设置最大buffer是 327675
    // set max send buffer
    int sendbuff = 327675;
    ecode = setsockopt(sock, SOL_SOCKET, SO_SNDBUF, &sendbuff, sizeof(sendbuff));
  
跟这个设置有关吗，调大点会不会不断开tcp

**Comment by sindney** [comment]
> 
> 
> loli_server.cpp里设置最大buffer是 327675
> // set max send buffer
> int sendbuff = 327675;
> ecode = setsockopt(sock, SOL_SOCKET, SO_SNDBUF, &sendbuff, sizeof(sendbuff));
> 
> 跟这个设置有关吗，调大点会不会不断开tcp

不好意思刚休假回来
应该没关系，有可能是瞬时网络包量太大了，可以尝试设置strict mode设置一个采集阈值，比如128/256byte以上再采集
或者用attach模式

也可以看看adb logcat -s Loli 看看设备上的socket是不是创建失败了，是不是ecode=-1
确保你的app开了internet access权限哈（mainfest）

**Comment by grystudy** [comment]
恩，网络应该正常，因为断开连接的现象是连接成功并正常记录一段时间后才出现的。好奇的问一下，为啥 “瞬时网络包量太大了” 会导致connect lost 呢？

**Comment by sindney** [comment]
具体原因我也没深究过，这个内存profile数据量是比较大，可能和adb socket的实现有关
也有可能是loli的server或client端设计不够健壮导致的
嗯 数据量确实大，pc上会把socket数据缓存到磁盘，一会就上G了，可能对disk的速度有写要求

**Comment by grystudy** [comment]
感谢
