### ISSUE TITLE
stacktrace显示unknown  如何解决

### ISSUE THREAD

**Issue by shaomluo** [Tencent/loli_profiler#25]
![image](https://user-images.githubusercontent.com/40687507/156738021-d387243f-14dd-439b-929d-028f44c12e91.png)
![image](https://user-images.githubusercontent.com/40687507/156738050-11dc9462-b451-42a5-8444-f5e35e3b580a.png)

**Comment by shaomluo** [comment]
大佬们帮忙看看阿

**Comment by shaomluo** [comment]
我这边显示hook正常
![VpsjMy0B28](https://user-images.githubusercontent.com/40687507/156743420-acfb208c-a29e-427e-a8eb-fd967cbaff47.png)

**Comment by shaomluo** [comment]
我在用nostack模式就不会显示unknown 怀疑是堆栈回溯过程出现问题了 请问有解决方法吗

**Comment by sindney** [comment]
你好，有按wiki改UE引擎了吗
framepointer模式最好只配置抓libUE4
unknown是smaps解析出错了
nostack用的另一种方式，给每个so一个hook函数，所以能直接知道是谁，不需要分析smaps

**Comment by shaomluo** [comment]
终于等到楼主了，这个问题没解决前，我会每天关注这个issue，希望能够尽快得到解决，感谢[❤]

**Comment by shaomluo** [comment]
有按操作文档改了引擎了的  上面不是framepointer模式只抓libUE4也是显示的unknown，我是看到网上有人多个so都hook成功 所以也尝试了下。

**Comment by shaomluo** [comment]
![image](https://user-images.githubusercontent.com/40687507/157171520-1bc074e6-397e-48bb-ba6d-40762d44bc46.png)
![image](https://user-images.githubusercontent.com/40687507/157171888-49e87601-c1a0-4ce1-8cd6-d2882e455524.png)
![image](https://user-images.githubusercontent.com/40687507/157171584-cea25cc7-e68b-4afe-a531-b16bf5eb7e20.png)
![image](https://user-images.githubusercontent.com/40687507/157171648-167cf824-bb4e-4587-a565-dbc26843f074.png)

**Comment by shaomluo** [comment]
请问还有什么原因导致显示不出来堆栈吗 这个是ue4自带的demo

**Comment by shaomluo** [comment]
对了 我用的是root的mi8 android10

**Comment by shaomluo** [comment]
ue4引擎4.27

**Comment by sindney** [comment]
多so如果要用framepointer需要所有so都开了相关的编译器选项
引擎、配置看上去都没啥问题
看上去和另一个与root设备相关的issue类似 #2 ，有别的设备吗？试试非root的机器
之前用的判断root设备的方案改成 -su 0，有条件了可以自己编译gui在qt里打断点看看
最快的方法还是换几台手机试试

**Comment by sindney** [comment]
原因的话就是profiler拿app的 smaps数据失败了
失败的原因应该是判断是否root设备在你的手机上失效

**Comment by shaomluo** [comment]
设备这个我可以尝试多几台看看，不过mi8这台我在$和su之间切换，发现stacktrace都是显示unknown。我试了下面这个命令行都是有数据的
adb shell run-as com.YourCompany.test "cat /proc/8899/smaps"，是否可以说明应该不是smaps导致的出错。
有条件了可以自己编译gui在qt里打断点看看。
----这个我尝试看看哈，我对C++不是很懂，代码能力有点弱（有点尴尬），可能不是一时半会能解决。
再次感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/loli_profiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/loli_profiler] stacktrace显示unknown  如何解决 (Issue #25)





 
原因的话就是profiler拿app的 smaps数据失败了
 失败的原因应该是判断是否root设备在你的手机上失效
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shaomluo** [comment]
因为居家办公，昨天才拿到1台非root的android设备oppo findx2，真的就可以了。有堆栈显示了，再次感谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/loli_profiler"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月9日(星期三) 中午11:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/loli_profiler] stacktrace显示unknown  如何解决 (Issue #25)





 
原因的话就是profiler拿app的 smaps数据失败了
 失败的原因应该是判断是否root设备在你的手机上失效
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sindney** [comment]
嗯 那估计还是我们目前没有一个比较通用的root设备判断方法
上次那个issue里的 su 0 在你这里又没效果了，那问题就是这个了
我就关单了哈
