### ISSUE TITLE
loli_profile可以定位出unity3d c#内存泄露代码吗？

### ISSUE THREAD

**Issue by HOTFIGHTER** [Tencent/loli_profiler#27]
如题，这边使用了unity3d c#写了一个可能内存泄露的地方，采用il2cpp编译，监控的so库是v8a的；
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Demo : MonoBehaviour
{
    private static Sprite leakOne;
    public Sprite testSprite;
    // Start is called before the first frame update
    void Start()
    {
        leakOne = testSprite;
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

**Comment by sindney** [comment]
il2cpp虚拟机需要改unity引擎把mono alloc、free转发出来，不改引擎只能看malloc内存

**Comment by HOTFIGHTER** [comment]
> il2cpp虚拟机需要改unity引擎把mono alloc、free转发出来，不改引擎只能看malloc内存

好的，那等于是对unity做不到无侵入式的内存泄露检测对吧？如果是这样的话，建议介绍里可以把unity的内存泄露监控去掉，现在来看在unity上这个框架其实意义不大，不知道我是否理解有误，望指教，谢谢

**Comment by HOTFIGHTER** [comment]
随便在问下，unreal上应该是可以正确分析内存泄露的是吧？

**Comment by sindney** [comment]
il2cpp内存和malloc内存是两回事，il2cpp内存一般都用mono的接口去分析，native内存 malloc内存是mono覆盖不到的
有真正的技术问题再提问吧
