### ISSUE TITLE
这个框架应该是夸大了它的能力，实际来看只能分析android原生场景的native内存泄露，对于unity是分析不了的，unreal的情况也抓不到任何数据

### ISSUE THREAD

**Issue by HOTFIGHTER** [Tencent/loli_profiler#28]
你好，这个框架说是有unity排查内存泄露的能力，实验下来是不行的，询问后又说需要unity mono层自己定位，unity是自己有profiler可以定位的，但是框架的开发目的就是替代这些能力；
是这样的如果做不到这些能力的话不应该写到readme里面来抬高自己框架的价值，谢谢！！

**Comment by sindney** [comment]
麻烦您先搞明白引擎不同模块内存的意义然后看看文档
https://github.com/Tencent/loli_profiler/blob/master/docs/GAME_ENGINE_CN.md
我们是开源技术交流，不是客服，不是教学，不负责helloworld级别的教学
