### ISSUE TITLE
一直提示Connection lost，无法抓取数据

### ISSUE THREAD

**Issue by coldfog** [Tencent/loli_profiler#29]
一直提示如下：
Starting application ...
Application Started!
Connecting to application server ... 
Connection lost ...
Kill your app or re-plug USB cable and try again.

翻了下FQA说是可能无法连接 apk中 的服务器，需要提供网络权限。目前判断网络权限应该是的，可以正常连接游戏服务器。是不是还需要前置的集成工作才能使用？logcat没有捕捉到相关的日志

**Comment by sindney** [comment]
有源码可以调试下拉起app的步骤
或者手动执行hook过程验证是否是机器环境问题

**Comment by coldfog** [comment]
多谢~解决了，原因是abi和so没匹配上，选择正确的abi就好了
