### ISSUE TITLE
那这么问吧，既然unity和unreal都能分析，这个框架ieg bg内有多少组是用的？

### ISSUE THREAD

**Issue by HOTFIGHTER** [Tencent/loli_profiler#30]
如题，之前提了两个issue指出了这个框架的局限性，指出了这个框架夸大了它的分析能力，建议作者修改readme文档，但是作者本跟不解释就直接关了issue，查了下作者还是腾讯比较高级的开发工程师！本人也是腾讯的工程师，这种态度实在不敢苟同

**Comment by HOTFIGHTER** [comment]
首先，对于unity最重要的内存分析就是unity mono层的分析，如果做不到就不能说是能对unity引擎进行内存泄露的监控，显然这个框架readme有明显的抬高自身的情况

**Comment by sindney** [comment]
内部有没有用可以自己去问，没必要在外部以没有一点技术含量的姿态和开发者沟通
如果看不懂readme可以问，看不懂代码可以去学习哈，mono内存去用另一款更简单的内部工具吧，这款有技术门槛，不建议您用
麻烦不要再骚扰了

**Comment by sindney** [comment]
PS
我不知道这位大哥，哪只眼睛看到我们的介绍有问题，unity引擎改法页再wiki了，就差把饭给大哥送到嘴里了：
Features

    Profiler client supports Windows 10/7 and Mac OSX Mojave and newer.
    Work with debuggable applications out of box.
    Support attaching to running application.
    Support multiple back-trace implementations.
    Support profiling complex games by doing some mods with your game engine.
    Support detecting c++ code memory leaks(Tested with Unreal Engine 4.26). 这条要是看不懂，我实在没办法了
    Support profiling release build applications on rooted devices.
    Multiple data view modes: tree map/call tree/memory fragmentation.

unity的mono泄漏和c++内存泄漏在底层完全就是两回事，我真的不想再给小白解释了，麻烦大哥别再提issue了，觉得我虚假宣传去内部bbs说把，看看谁对谁错，别在外面diuren了
就您这种人就是阻碍我们开源的最大源头
