### ISSUE TITLE
unity 2019.4解析不出来

### ISSUE THREAD

**Issue by redcard1** [Tencent/loli_profiler#36]
unity2019.4，unity和libil2cpp一直解析不出来，看到有生成libil2cpp.so.txt和libunity.so.txt都是有符号的
![image](https://user-images.githubusercontent.com/8540802/195784042-6337b6e2-8937-4e3a-a40e-45d32880bdd9.png)

**Comment by redcard1** [comment]
![image](https://user-images.githubusercontent.com/8540802/195786072-c497a964-056e-45e2-9b46-e96cea96e9dc.png)
我的配置是上图这样

**Comment by redcard1** [comment]
解决了，需要分两步，采集完再load symbol。。。

**Comment by redcard1** [comment]
by the way，能否支持下mmap的获取啊？

**Comment by sindney** [comment]
好，可以自己扩展下，因为mmap与malloc有关系，并且mmap拿到的大部分是内存池扩容堆栈（类似xcode allocations）
一般引擎抓内存也要切到系统malloc，为了通用，所以我们没做mmap的hook，有需要可以自己fork改
