### ISSUE TITLE
Cached 0 records.

### ISSUE THREAD

**Issue by feixiao** [Tencent/loli_profiler#37]
adb logcat -s Loli
--------- beginning of system
--------- beginning of main
10-25 12:52:29.793 11204 12234 I Loli    : Client disconnected, ecode: 0
10-25 12:53:21.589 12742 12742 I Loli    : JNI_OnLoad
10-25 12:53:21.589 12742 12742 I Loli    : mode: 0, build: default, minRecSize: 256, blacklist: 0, hookLibs: libunity,libil2cpp,
10-25 12:53:21.589 12742 12742 I Loli    : loli start status 0
10-25 12:53:24.429 12742 14281 I Loli    : Client connected
10-25 12:54:17.871 12742 14281 I Loli    : Client disconnected, ecode: 0

adb logcat -s xhook
--------- beginning of system
--------- beginning of main

OS: Android 10. 
Device: HONOR ViewPad 6

**Comment by sindney** [comment]
https://github.com/Tencent/loli_profiler/issues/21
https://github.com/Tencent/loli_profiler/issues/26

**Comment by feixiao** [comment]
> 
1:    apk's  flag is set to true.        check
2： apk has Internet Access.      check, ping pc is ok 
3:   Use adb logcat -s Loli to see application runtime logs.
--------- beginning of system
--------- beginning of main
10-26 01:24:23.873 17035 17109 I Loli    : Client disconnected, ecode: 0
10-26 01:26:04.662 17472 17472 I Loli    : JNI_OnLoad
10-26 01:26:04.662 17472 17472 I Loli    : mode: 0, build: default, minRecSize: 256, blacklist: 0, hookLibs: libunity,libil2cpp,
10-26 01:26:04.663 17472 17472 I Loli    : loli start status 0
10-26 01:26:07.693 17472 17511 I Loli    : Client connected
10-26 01:26:16.383 17472 17511 I Loli    : Client disconnected, ecode: 0

4： Use adb logcat -s xhook to see
--------- beginning of system
--------- beginning of main

OS: Android 10
Device：HONOR ViewPad 6, Pixel 3(root)
PC: MacBook Pro M1

**Comment by feixiao** [comment]
use black list will be ok
