### ISSUE TITLE
支持命令行调用吗

### ISSUE THREAD

**Issue by redcard1** [Tencent/loli_profiler#38]
你好，我们想集成到自动化测试中，想了解下是否支持命令行调用的方式

**Comment by sindney** [comment]
不支持自动化哈，我们暂时也没有计划实现可以自动化的版本，可以把核心逻辑整合到自己的工程中，输出符合loli 二进制格式的数据，离线使用UI进行debug等工作
或者改造一下qt前端，支持一下qt commandline的功能

**Comment by sindney** [comment]
这边暂无计划支持哈，因为引擎耦合度高，可以自行整合核心代码
