### ISSUE TITLE
captured 0 records：Error dlopen，试了好多设备都是如此

### ISSUE THREAD

**Issue by shaomluo** [Tencent/loli_profiler#39]
![mZ0Eq6I7UP](https://user-images.githubusercontent.com/40687507/203721309-479d2ef2-877c-4652-bad1-6d75a8ccc5b0.jpg)
试了好多设备都是如此，比如
1. Android 12，没root的 onePlus 9 pro  骁龙888
2. Android 12，root的 mi10 pro  骁龙865
3. Android 10，root的 mi8  骁龙845

用的是Ue4的 Demo工程，adb logcat -s Loli输出，求楼主看看还有救吗？祈求回复阿
C:\Users\luo>adb logcat -s Loli
--------- beginning of system
--------- beginning of main
11-24 09:41:11.508  7137  7137 I Loli    : JNI_OnLoad
11-24 09:41:11.509  7137  7137 I Loli    : mode: 1, build: default, minRecSize: 10240, blacklist: 0, hookLibs: libUE4.so,
11-24 09:41:11.510  7137  7137 I Loli    : loli start status 0
11-24 09:41:11.512  7137  7241 I Loli    : libUE4.so (/data/app/com.YourCompany.luo-NgvYhgqdItpy03Kvqg0OPA==/lib/arm64/libUE4.so) is loaded
11-24 09:41:11.526  7137  7241 I Loli    :  loaded in Android at 0x6ff93000
11-24 09:41:11.526  7137  7241 E Loli    : failed to open
11-24 09:41:11.526  7137  7241 I Loli    : Error dlopen:
11-24 09:41:11.541  7137  7241 I Loli    : All desired libraries are loaded.

**Comment by shaomluo** [comment]
![image](https://user-images.githubusercontent.com/40687507/203724015-d63fc761-1481-4932-ab73-f4f14b797d3f.png)

**Comment by sindney** [comment]
library配置时不要带.so，你看看wiki里哈，配置库都是不带.so的，直接写名字就行

**Comment by sindney** [comment]
看上去就是配置多带了 .so 有问题再reopen
