### ISSUE TITLE
关于 docs/GAME_ENGINE.md 这个说明的不懂之处

### ISSUE THREAD

**Issue by grystudy** [Tencent/loli_profiler#4]
大神 ，我想把文档都看懂一遍， Instrumented  和 Frame pointer 这两个优化的介绍我没太懂。
Unreal Engine 4 和 Unity Engine，是游戏引擎吗，是不是我们项目中没有用Unreal Engine 4 、Unity Engine这两个 ，我就不用看
 Instrumented  和 Frame pointer 这俩优化的介绍了。

**Comment by sindney** [comment]
Instrumented 你可以看高德地图的文章 https://developer.aliyun.com/article/708672
这俩都是编译器功能，Instrumented 简单讲就是让编译器在构建时，给所有函数头尾插入一个函数调用，这样我们就能自己写堆栈回溯（因为能拿到函数地址了），比默认的libunwind快十几倍
但必须得你的ndk里的gcc、clang支持这个编译器选项才行，并且你得重新编译代码
老板本的ndk不支持这个编译器选项的

当你的ndk很新时，比如r20，r21这种，就可以用更简单的Frame pointer编译器选项，简单讲就是占用一个寄存器，存储函数地址的指针，就能回溯堆栈了，这个是最快的

游戏引擎因为我们做游戏，所以我列出了怎么在引擎里加入这两种优化的方法
不是游戏也可以用相似的代码去优化你的app，如果你的app内存io并发量高的话

**Comment by grystudy** [comment]
好的 感谢！
