### ISSUE TITLE
unity 2019 "-fno-omit-frame-pointer" 选项可以做到debug包才生效吗？

### ISSUE THREAD

**Issue by riceliu** [Tencent/loli_profiler#40]
如题，我们这边可以修改uniyt引擎的源码，但是这个改动希望只对debug包生效，请问有什么办法吗？

改动：

// 修改文件： Tools/Bee/Bee.Toolchain.Android/AndroidNdkCompiler.cs
// if (Optimization != OptimizationLevel.None)
// {
//     // important for performance. Frame pointer is only useful for profiling, but
//     // introduces additional instructions into the prologue and epilogue of each function
//     // and leaves one less usable register.
//     yield return "-fomit-frame-pointer";
// }
yield return "-fno-omit-frame-pointer"; // <- 打开Framepointer选项

**Comment by sindney** [comment]
我没源码，不太清楚额，应该是可以的
