### ISSUE TITLE
macos 编译错误

### ISSUE THREAD

**Issue by hanbim520** [Tencent/loli_profiler#41]
<img width="604" alt="045554F1-CFC9-4F14-B27D-83658B40B282" src="https://user-images.githubusercontent.com/7490792/212065277-22d315a2-c1f2-4b8c-9fd5-b4c5cbd7fcee.png">

**Comment by sindney** [comment]
是使用我们提供的shell脚本发起构建的吗？我看你是要编arm64架构，这个我们确实没试过
暂时还没兼容过M1芯片的mac编译

**Comment by hanbim520** [comment]
是的，sh build.sh ，我的mac是mbp 13的m2处理器，可能和这个有关系

**Comment by hanbim520** [comment]
我对这个开源协议不了解，请问下，这个能否用在未购买QT授权的公司内使用呢

**Comment by sindney** [comment]
QT opensource好像是使用方必须开源才可以
嗯 我们确实没兼容过M1、2芯片的arm架构的MacOS
这块要支持的话可能需要一些工作量

**Comment by hanbim520** [comment]
好的，谢谢。
