### ISSUE TITLE
clang编译的so的Compiler该如何选择

### ISSUE THREAD

**Issue by lijunhuawhu** [Tencent/loli_profiler#5]
我写了一个ndk的demo，so是基于clang编译的，loli_profiler的配置如下，结果是始终连不上，请问这里的配置有问题吗？
![image](https://user-images.githubusercontent.com/7676643/113878140-ec26b300-97eb-11eb-9c0b-9825e8cd2187.png)

![image](https://user-images.githubusercontent.com/7676643/113878240-02347380-97ec-11eb-93b0-bd4393d74c33.png)

![image](https://user-images.githubusercontent.com/7676643/113878408-24c68c80-97ec-11eb-88bf-d328ecd5aa9c.png)

**Comment by sindney** [comment]
1.高版本安卓。设置下  android:extractNativeLibs，让so解压出来用，才能在maps里看到so
2.确认你的app申请了网络权限，拉起时 adb logcat -s Loli 看看运行时log信息，如果socket=-1就是网络权限没有

**Comment by lijunhuawhu** [comment]
好的，解决了，谢谢
