### ISSUE TITLE
为什么malloc的内存被free了，但是在Persistent选项中还是可以看到？如何监控app的内存泄漏？

### ISSUE THREAD

**Issue by lijunhuawhu** [Tencent/loli_profiler#6]
你好。我写一个demo测试了一下。在我的demo中，有一个按钮，每点击一次，都会创建一个线程；在这个线程中，通过jni调用了setValue()方法。
在setValue()方法中，有一个for循环，每1s钟通过malloc()分配了一个3.8M的内存；在setValue()的末尾又调用free()方法释放了内存；

我的问题是：
1. 为什么所有malloc的内存都free了，但是在Persistent选项中，还是看到了malloc()分配的内存？我看文档说，Persistent 选项会筛选出常驻内存，即未被释放的内存申请记录。这里的内存释放了，应该不是常驻内存的。
2. 为什么loli_profiler监控到的malloc()的调用次数比我实际在代码中调用的malloc()的次数要少得多？是因为有采样处理吗？
3. 如果我的so中有内存泄漏，我怎么样通过loli_profiler定位到呢？

![image](https://user-images.githubusercontent.com/7676643/114036234-7afe0300-98b2-11eb-89b3-6b1612fe3d1d.png)

![image](https://user-images.githubusercontent.com/7676643/114036355-9701a480-98b2-11eb-9062-874698402498.png)

**Comment by sindney** [comment]
你好 最近比较忙，没找到时间回复，抱歉
你可以通过adb logcat -s xhook确认free函数被正确hook，看是否有xh_ok的log
可能你的free因为什么原因没有hook上
内部代码你们也可以看到，内部对malloc free用atomic的变量进行排序，是正确支持多线程情况的。你的demo上层代码看不到，最好测试是主要逻辑写在native层，也方便我们目测debug。具体关于数据的采集请看使用wiki，有详细介绍不同设置的意义，我就不再赘述了

**Comment by sindney** [comment]
其次，如果只靠猜测，你的java层是起了新线程
但是你的native层代码（jni层）并不是线程安全的，p1等变量都不是thread_local，有线程安全问题
这个代码理论上有内存泄漏

**Comment by lijunhuawhu** [comment]
谢谢你在百忙之中的回复。是不是可以认为Persistent选项中看到的内存都内存泄漏的内存？不在Persistent选项中的内存就没有内存泄漏呢？

**Comment by sindney** [comment]
是的，目测你的代码有内存泄漏哈，我先close掉了，有疑问再reopen哈
