### ISSUE TITLE
loliprofiler连不上游戏

### ISSUE THREAD

**Issue by tencentgames** [Tencent/loli_profiler#7]
一直停在下面界面，连不上游戏，有什么讲究吗？多谢
![image](https://user-images.githubusercontent.com/10720636/114504900-27990580-9c62-11eb-818f-5be1bdfbe2f9.png)

**Comment by sindney** [comment]
根据wiki确认下你的配置是否正确，一般是配置错了
确认你们的游戏可以触发java层activity的 onResume回调（可以手动吧app切到后台再唤醒也能触发）
游戏一般不重新打包的话 可能无法使用，游戏建议按wiki'中该引擎的方法重新打包，再进行测试

**Comment by sindney** [comment]
暂时关闭了哈，还有问题再reopen
