### ISSUE TITLE
merged call stack 内容疑似错乱

### ISSUE THREAD

**Issue by grystudy** [Tencent/loli_profiler#8]
framepointer模式
threshold设置成0byte
如此便有大量的cache文件
stop后 loadsymbol

发现merged callstack的tree里面的堆栈错乱，怀疑是不是由于record量较大导致引起了bug？

**Comment by grystudy** [comment]
发现了一个规律 我的设备可能需要断电 重启 callstack才正常。
如果每次执行完一次统计，不断电重启，就会callstack错乱。
我自己先关了issue

**Comment by sindney** [comment]
好的，我没遇到过，后续如果有需要，把设备名和os等详细信息发下，我可以看能找到相同设备看看不
