### ISSUE TITLE
 MainWindow::InterpretRecordLibrary  代码临时变量命名可优化

### ISSUE THREAD

**Issue by grystudy** [Tencent/loli_profiler#9]
如下代码 for 中 定义int i。  在嵌套的另一个for中又定义一个 int i。  
c++ 这么写没有问题。
但不便于维护代码和后期修改。

void MainWindow::InterpretRecordLibrary(StackRecord& record, StacktraceData& data) {
    auto it = callStackMap_.find(record.uuid_);
    if (it == callStackMap_.end())
        return;
    auto& callStack = it.value();
    for (int i = 0; i < callStack.size(); i++) {
        auto& libName = callStack[i].first;
        auto& funcAddr = callStack[i].second;
        bool found = false;
        for (int i = 0; i < sMapsCache_.size(); i++) {
            const auto& cache = sMapsCache_[i];

**Comment by sindney** [comment]
这种代码问题可以提一个pr哈 感谢
